### ISSUE TITLE
The cup load is high when training

### ISSUE THREAD

**Issue by luzibuye** [IDEA-opensource/DN-DETR#11]
Hello, thanks for your wonderful work! 
I modified a little code to train on my own dataset (the same format as coco) but the cpu load seems a little high (over 50%). But when using [dab-detr](https://github.com/IDEA-opensource/DAB-DETR) to train the same dataset, the cpu load is very low. 
Is it normal or dose it need some improvement?

**Comment by FengLi-ust** [comment]
Hi, I have never noticed this problem on my GPU devices before, and I think the denoising processing does not require a heavy CPU load. If you find out the cause of this problem, you may share your opinions here.
