### ISSUE TITLE
Segmentation head

### ISSUE THREAD

**Issue by K-Mike** [IDEA-opensource/DN-DETR#14]
Hi,

Please, tell me how to run your code with segmentation head? --masks - doesn't work

**Comment by FengLi-ust** [comment]
DN-DETR aims at object detection. We have not tested the code of DETRsegm, hence there is no quality assurance of these codes.

**Comment by K-Mike** [comment]
Could you give me the code? I can fix for my-self, and maybe help you to test and refactor the code.

**Comment by FengLi-ust** [comment]
We have released all the code in DN-DETR and do not implement a segmentation head. You can try to adapt the original DETR segmentation head to DN-DETR for segmentation tasks.
