### ISSUE TITLE
num_classes

### ISSUE THREAD

**Issue by SangbumChoi** [IDEA-opensource/DN-DETR#15]
https://github.com/IDEA-opensource/DN-DETR/blob/206fa267ba7df978fa968edda9f7dd351a4b72c1/models/DN_DAB_DETR/DABDETR.py#L484

Hi thanks for wonderful repo.
Is there any reason the default num_cls = 20 for other dataset rather than coco?

**Comment by FengLi-ust** [comment]
Hi, this is directly copied from the original DAB-DETR repo (copied from the DETR repo). As we only use the coco dataset, therefore it is not used in our model. I guess it was used to support Pascal VOC dataset, which has 20 classes. You can ignore  it as both DAB-DETR and DN-DETR only report the coco results. Thank you.

**Comment by SangbumChoi** [comment]
Thank you for your reply hope to see in CVPR
