### ISSUE TITLE
Batch size effects

### ISSUE THREAD

**Issue by K-Mike** [IDEA-opensource/DN-DETR#16]
On my machine, I can only run a size 1 batch, how much will this degrade the results? I run with exactly the same parameters as yours the best one, except batch size, and the quality is much worse than MASK-RCNN
![Screenshot 2022-06-17 at 17 27 15](https://user-images.githubusercontent.com/22145213/174280611-79a089f0-7d05-43fa-a579-6435e4ced078.png)
.

**Comment by FengLi-ust** [comment]
As we mentioned in ReadMe, our model is sensitive to batch size (like most DETR-like models). Our default setting is 16 batch size to reproduce the reported results.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/34880758/174282292-f9555cda-d229-45da-a88d-cc841e388632.png">

**Comment by K-Mike** [comment]
Have you tried to accumulate gradient for multiple mini batches  to simulate a larger batch size?

**Comment by FengLi-ust** [comment]
No, I have not tried this yet.
