### ISSUE TITLE
How to use --drop_lr_now

### ISSUE THREAD

**Issue by LYMDLUT** [IDEA-opensource/DN-DETR#38]
Thank you for your excellent job! I wonder how to use  and when to use --drop_lr_now?
Thank you!

**Comment by FengLi-ust** [comment]
This is to drop the learning rate now. For example, if you train a 50 epoch result, you can use the 11th epoch checkpoint to drop its lr now and get 12 epoch (1x) setting results.

**Comment by LYMDLUT** [comment]
Thank you for your answer!
