### ISSUE TITLE
How do you solve the problem that the number of noising queries can't be same in a batch

### ISSUE THREAD

**Issue by volcanolee4** [IDEA-opensource/DN-DETR#8]
The number of  Ground Truth is different in different images, so the number of noising queries can't be same for the images in a same batch, how do you solve this problem?

**Comment by FengLi-ust** [comment]
There are 2 ways to solve this problem. In DN-DETR, we pad the noising queries in a batch to the same length. In DINO, we further propose a more efficient method named dynamic denoising groups, you can refer to [DINO](https://arxiv.org/abs/2203.03605) for more details. Thank you.

**Comment by volcanolee4** [comment]
Ok! Thanks for your reply!
